### ISSUE TITLE
With version 0.4.4 This Apworld is borked

### ISSUE THREAD

**Issue by BubbaSWalter** [Alchav/ootbijmqwt#1]
When trying to generate a multiworld with this apworld this error is thrown
[root at 2024-01-06 05:22:49,400]: Uncaught exception
Traceback (most recent call last):
  File "__startup__.py", line 124, in run
  File "console.py", line 16, in run
  File "Generate.py", line 653, in <module>
  File "Generate.py", line 239, in main
  File "Main.py", line 145, in main
  File "worlds\AutoWorld.py", line 154, in call_all
  File "worlds\AutoWorld.py", line 144, in call_single
  File "worlds\AutoWorld.py", line 137, in call_single
  File "worlds\AutoWorld.py", line 123, in _timed_call
  File "D:\Archipelago\lib\worlds\ootbijmqwt.apworld\ootbijmqwt\__init__.py", line 334, in set_rules
    set_entrances_based_rules(self)
  File "worlds\oot\Rules.py", line 230, in set_entrances_based_rules
  File "worlds\oot\__init__.py", line 1344, in get_state_with_complete_itempool
  File "worlds\AutoWorld.py", line 305, in __getattr__
AttributeError
Exception in <bound method OOTBIJMQWTWorld.set_rules of <worlds.ootbijmqwt.OOTBIJMQWTWorld object at 0x000001C61FD7F750>> for player 2, named Bubba WaterOoT.

**Comment by Alchav** [comment]
Wow, someone is trying to play this?

**Comment by Alchav** [comment]
@BubbaSWalter I just published a new release. I was able to generate with the default yaml settings but did no testing with other options. Hopefully everything is working now. Thanks for the report.

**Comment by BubbaSWalter** [comment]
Yes,  I find this one quite fun.
________________________________
